name: Update Gold Market Data

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

# جلوگیری از اجرای همزمان چند Update
concurrency:
  group: gold-market-update
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  collect:

    runs-on: ubuntu-latest

    steps:

      - name: Get latest repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # اول آخرین نسخه main را می‌گیریم
      - name: Sync with latest main
        run: |
          git fetch origin main
          git reset --hard origin/main

      # دریافت قیمت و آرشیو
      - name: Collect latest gold data
        run: |
          python collector.py

      # ثبت تغییر JSON
      - name: Commit updated JSON
        run: |

          git config user.name "gold-data-bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/market.json

          if git diff --cached --quiet; then
            echo "No new market data."
            exit 0
          fi

          git commit -m "Update gold market data"

      # گرفتن آخرین تغییرات درست قبل از Push
      - name: Sync before push
        run: |
          git fetch origin main

          git rebase origin/main || {
            echo "Rebase conflict detected."

            git checkout --theirs data/market.json
            git add data/market.json

            GIT_EDITOR=true git rebase --continue
          }

      # ارسال به GitHub
      - name: Push updated JSON
        run: |
          git push origin HEAD:main
